/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ClimateService } from "../climate.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ClimateCreateInput } from "./ClimateCreateInput";
import { Climate } from "./Climate";
import { ClimateFindManyArgs } from "./ClimateFindManyArgs";
import { ClimateWhereUniqueInput } from "./ClimateWhereUniqueInput";
import { ClimateUpdateInput } from "./ClimateUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ClimateControllerBase {
  constructor(
    protected readonly service: ClimateService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Climate })
  @nestAccessControl.UseRoles({
    resource: "Climate",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createClimate(
    @common.Body() data: ClimateCreateInput
  ): Promise<Climate> {
    return await this.service.createClimate({
      data: data,
      select: {
        accessToClimateInformation: true,
        averageAnnualRainfall: true,
        averageTemperature: true,
        climateType: true,
        commonWeatherEvents: true,
        createdAt: true,
        id: true,
        impactOnLivelihood: true,
        seasonalChanges: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Climate] })
  @ApiNestedQuery(ClimateFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Climate",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async climates(@common.Req() request: Request): Promise<Climate[]> {
    const args = plainToClass(ClimateFindManyArgs, request.query);
    return this.service.climates({
      ...args,
      select: {
        accessToClimateInformation: true,
        averageAnnualRainfall: true,
        averageTemperature: true,
        climateType: true,
        commonWeatherEvents: true,
        createdAt: true,
        id: true,
        impactOnLivelihood: true,
        seasonalChanges: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Climate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Climate",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async climate(
    @common.Param() params: ClimateWhereUniqueInput
  ): Promise<Climate | null> {
    const result = await this.service.climate({
      where: params,
      select: {
        accessToClimateInformation: true,
        averageAnnualRainfall: true,
        averageTemperature: true,
        climateType: true,
        commonWeatherEvents: true,
        createdAt: true,
        id: true,
        impactOnLivelihood: true,
        seasonalChanges: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Climate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Climate",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateClimate(
    @common.Param() params: ClimateWhereUniqueInput,
    @common.Body() data: ClimateUpdateInput
  ): Promise<Climate | null> {
    try {
      return await this.service.updateClimate({
        where: params,
        data: data,
        select: {
          accessToClimateInformation: true,
          averageAnnualRainfall: true,
          averageTemperature: true,
          climateType: true,
          commonWeatherEvents: true,
          createdAt: true,
          id: true,
          impactOnLivelihood: true,
          seasonalChanges: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Climate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Climate",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteClimate(
    @common.Param() params: ClimateWhereUniqueInput
  ): Promise<Climate | null> {
    try {
      return await this.service.deleteClimate({
        where: params,
        select: {
          accessToClimateInformation: true,
          averageAnnualRainfall: true,
          averageTemperature: true,
          climateType: true,
          commonWeatherEvents: true,
          createdAt: true,
          id: true,
          impactOnLivelihood: true,
          seasonalChanges: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
