/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HouseholdsCharacteristicsService } from "../householdsCharacteristics.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HouseholdsCharacteristicsCreateInput } from "./HouseholdsCharacteristicsCreateInput";
import { HouseholdsCharacteristics } from "./HouseholdsCharacteristics";
import { HouseholdsCharacteristicsFindManyArgs } from "./HouseholdsCharacteristicsFindManyArgs";
import { HouseholdsCharacteristicsWhereUniqueInput } from "./HouseholdsCharacteristicsWhereUniqueInput";
import { HouseholdsCharacteristicsUpdateInput } from "./HouseholdsCharacteristicsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HouseholdsCharacteristicsControllerBase {
  constructor(
    protected readonly service: HouseholdsCharacteristicsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HouseholdsCharacteristics })
  @nestAccessControl.UseRoles({
    resource: "HouseholdsCharacteristics",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createHouseholdsCharacteristics(
    @common.Body() data: HouseholdsCharacteristicsCreateInput
  ): Promise<HouseholdsCharacteristics> {
    return await this.service.createHouseholdsCharacteristics({
      data: data,
      select: {
        createdAt: true,
        headOfHousehold: true,
        householdIncome: true,
        id: true,
        mainSourceOfIncome: true,
        monthlyExpenses: true,
        numberOfDependents: true,
        numberOfEmployedMembers: true,
        numberOfMembers: true,
        primaryLanguageSpoken: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [HouseholdsCharacteristics] })
  @ApiNestedQuery(HouseholdsCharacteristicsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "HouseholdsCharacteristics",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async householdsCharacteristicsItems(
    @common.Req() request: Request
  ): Promise<HouseholdsCharacteristics[]> {
    const args = plainToClass(
      HouseholdsCharacteristicsFindManyArgs,
      request.query
    );
    return this.service.householdsCharacteristicsItems({
      ...args,
      select: {
        createdAt: true,
        headOfHousehold: true,
        householdIncome: true,
        id: true,
        mainSourceOfIncome: true,
        monthlyExpenses: true,
        numberOfDependents: true,
        numberOfEmployedMembers: true,
        numberOfMembers: true,
        primaryLanguageSpoken: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HouseholdsCharacteristics })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HouseholdsCharacteristics",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async householdsCharacteristics(
    @common.Param() params: HouseholdsCharacteristicsWhereUniqueInput
  ): Promise<HouseholdsCharacteristics | null> {
    const result = await this.service.householdsCharacteristics({
      where: params,
      select: {
        createdAt: true,
        headOfHousehold: true,
        householdIncome: true,
        id: true,
        mainSourceOfIncome: true,
        monthlyExpenses: true,
        numberOfDependents: true,
        numberOfEmployedMembers: true,
        numberOfMembers: true,
        primaryLanguageSpoken: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HouseholdsCharacteristics })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HouseholdsCharacteristics",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateHouseholdsCharacteristics(
    @common.Param() params: HouseholdsCharacteristicsWhereUniqueInput,
    @common.Body() data: HouseholdsCharacteristicsUpdateInput
  ): Promise<HouseholdsCharacteristics | null> {
    try {
      return await this.service.updateHouseholdsCharacteristics({
        where: params,
        data: data,
        select: {
          createdAt: true,
          headOfHousehold: true,
          householdIncome: true,
          id: true,
          mainSourceOfIncome: true,
          monthlyExpenses: true,
          numberOfDependents: true,
          numberOfEmployedMembers: true,
          numberOfMembers: true,
          primaryLanguageSpoken: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HouseholdsCharacteristics })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HouseholdsCharacteristics",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteHouseholdsCharacteristics(
    @common.Param() params: HouseholdsCharacteristicsWhereUniqueInput
  ): Promise<HouseholdsCharacteristics | null> {
    try {
      return await this.service.deleteHouseholdsCharacteristics({
        where: params,
        select: {
          createdAt: true,
          headOfHousehold: true,
          householdIncome: true,
          id: true,
          mainSourceOfIncome: true,
          monthlyExpenses: true,
          numberOfDependents: true,
          numberOfEmployedMembers: true,
          numberOfMembers: true,
          primaryLanguageSpoken: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
