/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AgricultureFarmingService } from "../agricultureFarming.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AgricultureFarmingCreateInput } from "./AgricultureFarmingCreateInput";
import { AgricultureFarming } from "./AgricultureFarming";
import { AgricultureFarmingFindManyArgs } from "./AgricultureFarmingFindManyArgs";
import { AgricultureFarmingWhereUniqueInput } from "./AgricultureFarmingWhereUniqueInput";
import { AgricultureFarmingUpdateInput } from "./AgricultureFarmingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AgricultureFarmingControllerBase {
  constructor(
    protected readonly service: AgricultureFarmingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AgricultureFarming })
  @nestAccessControl.UseRoles({
    resource: "AgricultureFarming",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAgricultureFarming(
    @common.Body() data: AgricultureFarmingCreateInput
  ): Promise<AgricultureFarming> {
    return await this.service.createAgricultureFarming({
      data: data,
      select: {
        accessToAgriculturalSupport: true,
        annualYield: true,
        areaCultivated: true,
        commonPestsAndDiseases: true,
        createdAt: true,
        farmingEquipmentUsed: true,
        id: true,
        irrigationMethod: true,
        typeOfCropsGrown: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AgricultureFarming] })
  @ApiNestedQuery(AgricultureFarmingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AgricultureFarming",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async agricultureFarmings(
    @common.Req() request: Request
  ): Promise<AgricultureFarming[]> {
    const args = plainToClass(AgricultureFarmingFindManyArgs, request.query);
    return this.service.agricultureFarmings({
      ...args,
      select: {
        accessToAgriculturalSupport: true,
        annualYield: true,
        areaCultivated: true,
        commonPestsAndDiseases: true,
        createdAt: true,
        farmingEquipmentUsed: true,
        id: true,
        irrigationMethod: true,
        typeOfCropsGrown: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AgricultureFarming })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AgricultureFarming",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async agricultureFarming(
    @common.Param() params: AgricultureFarmingWhereUniqueInput
  ): Promise<AgricultureFarming | null> {
    const result = await this.service.agricultureFarming({
      where: params,
      select: {
        accessToAgriculturalSupport: true,
        annualYield: true,
        areaCultivated: true,
        commonPestsAndDiseases: true,
        createdAt: true,
        farmingEquipmentUsed: true,
        id: true,
        irrigationMethod: true,
        typeOfCropsGrown: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AgricultureFarming })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AgricultureFarming",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAgricultureFarming(
    @common.Param() params: AgricultureFarmingWhereUniqueInput,
    @common.Body() data: AgricultureFarmingUpdateInput
  ): Promise<AgricultureFarming | null> {
    try {
      return await this.service.updateAgricultureFarming({
        where: params,
        data: data,
        select: {
          accessToAgriculturalSupport: true,
          annualYield: true,
          areaCultivated: true,
          commonPestsAndDiseases: true,
          createdAt: true,
          farmingEquipmentUsed: true,
          id: true,
          irrigationMethod: true,
          typeOfCropsGrown: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AgricultureFarming })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AgricultureFarming",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAgricultureFarming(
    @common.Param() params: AgricultureFarmingWhereUniqueInput
  ): Promise<AgricultureFarming | null> {
    try {
      return await this.service.deleteAgricultureFarming({
        where: params,
        select: {
          accessToAgriculturalSupport: true,
          annualYield: true,
          areaCultivated: true,
          commonPestsAndDiseases: true,
          createdAt: true,
          farmingEquipmentUsed: true,
          id: true,
          irrigationMethod: true,
          typeOfCropsGrown: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
