/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsEnum,
  IsOptional,
  IsInt,
  Min,
  Max,
  IsString,
  MaxLength,
  IsNumber,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumEconomicActivityEmploymentStatus } from "./EnumEconomicActivityEmploymentStatus";
import { EnumEconomicActivityTypeOfEmployment } from "./EnumEconomicActivityTypeOfEmployment";

@ObjectType()
class EconomicActivity {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    enum: EnumEconomicActivityEmploymentStatus,
  })
  @IsEnum(EnumEconomicActivityEmploymentStatus)
  @IsOptional()
  @Field(() => EnumEconomicActivityEmploymentStatus, {
    nullable: true,
  })
  employmentStatus?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  hoursWorkedPerWeek!: number | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  industry!: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  monthlyIncome!: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  occupation!: string | null;

  @ApiProperty({
    required: false,
    enum: EnumEconomicActivityTypeOfEmployment,
  })
  @IsEnum(EnumEconomicActivityTypeOfEmployment)
  @IsOptional()
  @Field(() => EnumEconomicActivityTypeOfEmployment, {
    nullable: true,
  })
  typeOfEmployment?: "Option1" | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  workplaceAddress!: string | null;
}

export { EconomicActivity as EconomicActivity };
