/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumEconomicActivityEmploymentStatus } from "./EnumEconomicActivityEmploymentStatus";
import { IsEnum, IsOptional } from "class-validator";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { Type } from "class-transformer";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { EnumEconomicActivityTypeOfEmployment } from "./EnumEconomicActivityTypeOfEmployment";

@InputType()
class EconomicActivityWhereInput {
  @ApiProperty({
    required: false,
    enum: EnumEconomicActivityEmploymentStatus,
  })
  @IsEnum(EnumEconomicActivityEmploymentStatus)
  @IsOptional()
  @Field(() => EnumEconomicActivityEmploymentStatus, {
    nullable: true,
  })
  employmentStatus?: "Option1";

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  hoursWorkedPerWeek?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  industry?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  monthlyIncome?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  occupation?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumEconomicActivityTypeOfEmployment,
  })
  @IsEnum(EnumEconomicActivityTypeOfEmployment)
  @IsOptional()
  @Field(() => EnumEconomicActivityTypeOfEmployment, {
    nullable: true,
  })
  typeOfEmployment?: "Option1";

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  workplaceAddress?: StringNullableFilter;
}

export { EconomicActivityWhereInput as EconomicActivityWhereInput };
