/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsString,
  MaxLength,
  IsOptional,
  IsEnum,
  IsNumber,
  Min,
  Max,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumSalariesAndWagesFrequencyOfPayment } from "./EnumSalariesAndWagesFrequencyOfPayment";
import { EnumSalariesAndWagesTypeOfEmployment } from "./EnumSalariesAndWagesTypeOfEmployment";

@ObjectType()
class SalariesAndWages {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  employerName!: string | null;

  @ApiProperty({
    required: false,
    enum: EnumSalariesAndWagesFrequencyOfPayment,
  })
  @IsEnum(EnumSalariesAndWagesFrequencyOfPayment)
  @IsOptional()
  @Field(() => EnumSalariesAndWagesFrequencyOfPayment, {
    nullable: true,
  })
  frequencyOfPayment?: "Option1" | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  jobTitle!: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  monthlySalary!: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  otherBenefits!: string | null;

  @ApiProperty({
    required: false,
    enum: EnumSalariesAndWagesTypeOfEmployment,
  })
  @IsEnum(EnumSalariesAndWagesTypeOfEmployment)
  @IsOptional()
  @Field(() => EnumSalariesAndWagesTypeOfEmployment, {
    nullable: true,
  })
  typeOfEmployment?: "Option1" | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { SalariesAndWages as SalariesAndWages };
