/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum } from "class-validator";
import { EnumSalariesAndWagesFrequencyOfPayment } from "./EnumSalariesAndWagesFrequencyOfPayment";
import { StringFilter } from "../../util/StringFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { EnumSalariesAndWagesTypeOfEmployment } from "./EnumSalariesAndWagesTypeOfEmployment";

@InputType()
class SalariesAndWagesWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  employerName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumSalariesAndWagesFrequencyOfPayment,
  })
  @IsEnum(EnumSalariesAndWagesFrequencyOfPayment)
  @IsOptional()
  @Field(() => EnumSalariesAndWagesFrequencyOfPayment, {
    nullable: true,
  })
  frequencyOfPayment?: "Option1";

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  jobTitle?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  monthlySalary?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  otherBenefits?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumSalariesAndWagesTypeOfEmployment,
  })
  @IsEnum(EnumSalariesAndWagesTypeOfEmployment)
  @IsOptional()
  @Field(() => EnumSalariesAndWagesTypeOfEmployment, {
    nullable: true,
  })
  typeOfEmployment?: "Option1";
}

export { SalariesAndWagesWhereInput as SalariesAndWagesWhereInput };
