/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum } from "class-validator";
import { EnumWasteManagementFrequencyOfWasteCollection } from "./EnumWasteManagementFrequencyOfWasteCollection";
import { EnumWasteManagementHazardousWasteDisposal } from "./EnumWasteManagementHazardousWasteDisposal";
import { StringFilter } from "../../util/StringFilter";
import { EnumWasteManagementWasteDisposalMethod } from "./EnumWasteManagementWasteDisposalMethod";

@InputType()
class WasteManagementWhereInput {
  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  compostingPractices?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumWasteManagementFrequencyOfWasteCollection,
  })
  @IsEnum(EnumWasteManagementFrequencyOfWasteCollection)
  @IsOptional()
  @Field(() => EnumWasteManagementFrequencyOfWasteCollection, {
    nullable: true,
  })
  frequencyOfWasteCollection?: "Option1";

  @ApiProperty({
    required: false,
    enum: EnumWasteManagementHazardousWasteDisposal,
  })
  @IsEnum(EnumWasteManagementHazardousWasteDisposal)
  @IsOptional()
  @Field(() => EnumWasteManagementHazardousWasteDisposal, {
    nullable: true,
  })
  hazardousWasteDisposal?: "Option1";

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  recyclingPractices?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumWasteManagementWasteDisposalMethod,
  })
  @IsEnum(EnumWasteManagementWasteDisposalMethod)
  @IsOptional()
  @Field(() => EnumWasteManagementWasteDisposalMethod, {
    nullable: true,
  })
  wasteDisposalMethod?: "Option1";

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  wasteSegregationPractices?: BooleanNullableFilter;
}

export { WasteManagementWhereInput as WasteManagementWhereInput };
