/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { WasteManagementService } from "../wasteManagement.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WasteManagementCreateInput } from "./WasteManagementCreateInput";
import { WasteManagement } from "./WasteManagement";
import { WasteManagementFindManyArgs } from "./WasteManagementFindManyArgs";
import { WasteManagementWhereUniqueInput } from "./WasteManagementWhereUniqueInput";
import { WasteManagementUpdateInput } from "./WasteManagementUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WasteManagementControllerBase {
  constructor(
    protected readonly service: WasteManagementService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WasteManagement })
  @nestAccessControl.UseRoles({
    resource: "WasteManagement",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createWasteManagement(
    @common.Body() data: WasteManagementCreateInput
  ): Promise<WasteManagement> {
    return await this.service.createWasteManagement({
      data: data,
      select: {
        compostingPractices: true,
        createdAt: true,
        frequencyOfWasteCollection: true,
        hazardousWasteDisposal: true,
        id: true,
        recyclingPractices: true,
        updatedAt: true,
        wasteDisposalMethod: true,
        wasteSegregationPractices: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [WasteManagement] })
  @ApiNestedQuery(WasteManagementFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "WasteManagement",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async wasteManagements(
    @common.Req() request: Request
  ): Promise<WasteManagement[]> {
    const args = plainToClass(WasteManagementFindManyArgs, request.query);
    return this.service.wasteManagements({
      ...args,
      select: {
        compostingPractices: true,
        createdAt: true,
        frequencyOfWasteCollection: true,
        hazardousWasteDisposal: true,
        id: true,
        recyclingPractices: true,
        updatedAt: true,
        wasteDisposalMethod: true,
        wasteSegregationPractices: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WasteManagement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WasteManagement",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async wasteManagement(
    @common.Param() params: WasteManagementWhereUniqueInput
  ): Promise<WasteManagement | null> {
    const result = await this.service.wasteManagement({
      where: params,
      select: {
        compostingPractices: true,
        createdAt: true,
        frequencyOfWasteCollection: true,
        hazardousWasteDisposal: true,
        id: true,
        recyclingPractices: true,
        updatedAt: true,
        wasteDisposalMethod: true,
        wasteSegregationPractices: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WasteManagement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WasteManagement",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateWasteManagement(
    @common.Param() params: WasteManagementWhereUniqueInput,
    @common.Body() data: WasteManagementUpdateInput
  ): Promise<WasteManagement | null> {
    try {
      return await this.service.updateWasteManagement({
        where: params,
        data: data,
        select: {
          compostingPractices: true,
          createdAt: true,
          frequencyOfWasteCollection: true,
          hazardousWasteDisposal: true,
          id: true,
          recyclingPractices: true,
          updatedAt: true,
          wasteDisposalMethod: true,
          wasteSegregationPractices: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WasteManagement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WasteManagement",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWasteManagement(
    @common.Param() params: WasteManagementWhereUniqueInput
  ): Promise<WasteManagement | null> {
    try {
      return await this.service.deleteWasteManagement({
        where: params,
        select: {
          compostingPractices: true,
          createdAt: true,
          frequencyOfWasteCollection: true,
          hazardousWasteDisposal: true,
          id: true,
          recyclingPractices: true,
          updatedAt: true,
          wasteDisposalMethod: true,
          wasteSegregationPractices: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
