/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HousingService } from "../housing.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HousingCreateInput } from "./HousingCreateInput";
import { Housing } from "./Housing";
import { HousingFindManyArgs } from "./HousingFindManyArgs";
import { HousingWhereUniqueInput } from "./HousingWhereUniqueInput";
import { HousingUpdateInput } from "./HousingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HousingControllerBase {
  constructor(
    protected readonly service: HousingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Housing })
  @nestAccessControl.UseRoles({
    resource: "Housing",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createHousing(
    @common.Body() data: HousingCreateInput
  ): Promise<Housing> {
    return await this.service.createHousing({
      data: data,
      select: {
        constructionMaterial: true,
        createdAt: true,
        electricityAccess: true,
        houseType: true,
        id: true,
        neighborhoodType: true,
        numberOfRooms: true,
        ownershipStatus: true,
        proximityToEssentialServices: true,
        updatedAt: true,
        yearBuilt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Housing] })
  @ApiNestedQuery(HousingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Housing",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async housings(@common.Req() request: Request): Promise<Housing[]> {
    const args = plainToClass(HousingFindManyArgs, request.query);
    return this.service.housings({
      ...args,
      select: {
        constructionMaterial: true,
        createdAt: true,
        electricityAccess: true,
        houseType: true,
        id: true,
        neighborhoodType: true,
        numberOfRooms: true,
        ownershipStatus: true,
        proximityToEssentialServices: true,
        updatedAt: true,
        yearBuilt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Housing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Housing",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async housing(
    @common.Param() params: HousingWhereUniqueInput
  ): Promise<Housing | null> {
    const result = await this.service.housing({
      where: params,
      select: {
        constructionMaterial: true,
        createdAt: true,
        electricityAccess: true,
        houseType: true,
        id: true,
        neighborhoodType: true,
        numberOfRooms: true,
        ownershipStatus: true,
        proximityToEssentialServices: true,
        updatedAt: true,
        yearBuilt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Housing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Housing",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateHousing(
    @common.Param() params: HousingWhereUniqueInput,
    @common.Body() data: HousingUpdateInput
  ): Promise<Housing | null> {
    try {
      return await this.service.updateHousing({
        where: params,
        data: data,
        select: {
          constructionMaterial: true,
          createdAt: true,
          electricityAccess: true,
          houseType: true,
          id: true,
          neighborhoodType: true,
          numberOfRooms: true,
          ownershipStatus: true,
          proximityToEssentialServices: true,
          updatedAt: true,
          yearBuilt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Housing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Housing",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteHousing(
    @common.Param() params: HousingWhereUniqueInput
  ): Promise<Housing | null> {
    try {
      return await this.service.deleteHousing({
        where: params,
        select: {
          constructionMaterial: true,
          createdAt: true,
          electricityAccess: true,
          houseType: true,
          id: true,
          neighborhoodType: true,
          numberOfRooms: true,
          ownershipStatus: true,
          proximityToEssentialServices: true,
          updatedAt: true,
          yearBuilt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
