/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SourceOfIncomeService } from "../sourceOfIncome.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SourceOfIncomeCreateInput } from "./SourceOfIncomeCreateInput";
import { SourceOfIncome } from "./SourceOfIncome";
import { SourceOfIncomeFindManyArgs } from "./SourceOfIncomeFindManyArgs";
import { SourceOfIncomeWhereUniqueInput } from "./SourceOfIncomeWhereUniqueInput";
import { SourceOfIncomeUpdateInput } from "./SourceOfIncomeUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SourceOfIncomeControllerBase {
  constructor(
    protected readonly service: SourceOfIncomeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SourceOfIncome })
  @nestAccessControl.UseRoles({
    resource: "SourceOfIncome",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSourceOfIncome(
    @common.Body() data: SourceOfIncomeCreateInput
  ): Promise<SourceOfIncome> {
    return await this.service.createSourceOfIncome({
      data: data,
      select: {
        amountFromPrimarySource: true,
        amountFromSecondarySource: true,
        createdAt: true,
        frequencyOfIncome: true,
        id: true,
        otherSourcesOfIncome: true,
        primarySourceOfIncome: true,
        secondarySourceOfIncome: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [SourceOfIncome] })
  @ApiNestedQuery(SourceOfIncomeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "SourceOfIncome",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async sourceOfIncomes(
    @common.Req() request: Request
  ): Promise<SourceOfIncome[]> {
    const args = plainToClass(SourceOfIncomeFindManyArgs, request.query);
    return this.service.sourceOfIncomes({
      ...args,
      select: {
        amountFromPrimarySource: true,
        amountFromSecondarySource: true,
        createdAt: true,
        frequencyOfIncome: true,
        id: true,
        otherSourcesOfIncome: true,
        primarySourceOfIncome: true,
        secondarySourceOfIncome: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SourceOfIncome })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SourceOfIncome",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async sourceOfIncome(
    @common.Param() params: SourceOfIncomeWhereUniqueInput
  ): Promise<SourceOfIncome | null> {
    const result = await this.service.sourceOfIncome({
      where: params,
      select: {
        amountFromPrimarySource: true,
        amountFromSecondarySource: true,
        createdAt: true,
        frequencyOfIncome: true,
        id: true,
        otherSourcesOfIncome: true,
        primarySourceOfIncome: true,
        secondarySourceOfIncome: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SourceOfIncome })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SourceOfIncome",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSourceOfIncome(
    @common.Param() params: SourceOfIncomeWhereUniqueInput,
    @common.Body() data: SourceOfIncomeUpdateInput
  ): Promise<SourceOfIncome | null> {
    try {
      return await this.service.updateSourceOfIncome({
        where: params,
        data: data,
        select: {
          amountFromPrimarySource: true,
          amountFromSecondarySource: true,
          createdAt: true,
          frequencyOfIncome: true,
          id: true,
          otherSourcesOfIncome: true,
          primarySourceOfIncome: true,
          secondarySourceOfIncome: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SourceOfIncome })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "SourceOfIncome",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSourceOfIncome(
    @common.Param() params: SourceOfIncomeWhereUniqueInput
  ): Promise<SourceOfIncome | null> {
    try {
      return await this.service.deleteSourceOfIncome({
        where: params,
        select: {
          amountFromPrimarySource: true,
          amountFromSecondarySource: true,
          createdAt: true,
          frequencyOfIncome: true,
          id: true,
          otherSourcesOfIncome: true,
          primarySourceOfIncome: true,
          secondarySourceOfIncome: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
