/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { WaterAndSanitationService } from "../waterAndSanitation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WaterAndSanitationCreateInput } from "./WaterAndSanitationCreateInput";
import { WaterAndSanitation } from "./WaterAndSanitation";
import { WaterAndSanitationFindManyArgs } from "./WaterAndSanitationFindManyArgs";
import { WaterAndSanitationWhereUniqueInput } from "./WaterAndSanitationWhereUniqueInput";
import { WaterAndSanitationUpdateInput } from "./WaterAndSanitationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WaterAndSanitationControllerBase {
  constructor(
    protected readonly service: WaterAndSanitationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WaterAndSanitation })
  @nestAccessControl.UseRoles({
    resource: "WaterAndSanitation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createWaterAndSanitation(
    @common.Body() data: WaterAndSanitationCreateInput
  ): Promise<WaterAndSanitation> {
    return await this.service.createWaterAndSanitation({
      data: data,
      select: {
        accessToSanitationFacility: true,
        createdAt: true,
        frequencyOfWasteCollection: true,
        id: true,
        sanitationFacilityType: true,
        updatedAt: true,
        wastewaterDisposalMethod: true,
        waterAvailability: true,
        waterQuality: true,
        waterSource: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [WaterAndSanitation] })
  @ApiNestedQuery(WaterAndSanitationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "WaterAndSanitation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async waterAndSanitations(
    @common.Req() request: Request
  ): Promise<WaterAndSanitation[]> {
    const args = plainToClass(WaterAndSanitationFindManyArgs, request.query);
    return this.service.waterAndSanitations({
      ...args,
      select: {
        accessToSanitationFacility: true,
        createdAt: true,
        frequencyOfWasteCollection: true,
        id: true,
        sanitationFacilityType: true,
        updatedAt: true,
        wastewaterDisposalMethod: true,
        waterAvailability: true,
        waterQuality: true,
        waterSource: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WaterAndSanitation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WaterAndSanitation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async waterAndSanitation(
    @common.Param() params: WaterAndSanitationWhereUniqueInput
  ): Promise<WaterAndSanitation | null> {
    const result = await this.service.waterAndSanitation({
      where: params,
      select: {
        accessToSanitationFacility: true,
        createdAt: true,
        frequencyOfWasteCollection: true,
        id: true,
        sanitationFacilityType: true,
        updatedAt: true,
        wastewaterDisposalMethod: true,
        waterAvailability: true,
        waterQuality: true,
        waterSource: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WaterAndSanitation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WaterAndSanitation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateWaterAndSanitation(
    @common.Param() params: WaterAndSanitationWhereUniqueInput,
    @common.Body() data: WaterAndSanitationUpdateInput
  ): Promise<WaterAndSanitation | null> {
    try {
      return await this.service.updateWaterAndSanitation({
        where: params,
        data: data,
        select: {
          accessToSanitationFacility: true,
          createdAt: true,
          frequencyOfWasteCollection: true,
          id: true,
          sanitationFacilityType: true,
          updatedAt: true,
          wastewaterDisposalMethod: true,
          waterAvailability: true,
          waterQuality: true,
          waterSource: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WaterAndSanitation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WaterAndSanitation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWaterAndSanitation(
    @common.Param() params: WaterAndSanitationWhereUniqueInput
  ): Promise<WaterAndSanitation | null> {
    try {
      return await this.service.deleteWaterAndSanitation({
        where: params,
        select: {
          accessToSanitationFacility: true,
          createdAt: true,
          frequencyOfWasteCollection: true,
          id: true,
          sanitationFacilityType: true,
          updatedAt: true,
          wastewaterDisposalMethod: true,
          waterAvailability: true,
          waterQuality: true,
          waterSource: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
