/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HealthAndOtherCharacteristicsService } from "../healthAndOtherCharacteristics.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HealthAndOtherCharacteristicsCreateInput } from "./HealthAndOtherCharacteristicsCreateInput";
import { HealthAndOtherCharacteristics } from "./HealthAndOtherCharacteristics";
import { HealthAndOtherCharacteristicsFindManyArgs } from "./HealthAndOtherCharacteristicsFindManyArgs";
import { HealthAndOtherCharacteristicsWhereUniqueInput } from "./HealthAndOtherCharacteristicsWhereUniqueInput";
import { HealthAndOtherCharacteristicsUpdateInput } from "./HealthAndOtherCharacteristicsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HealthAndOtherCharacteristicsControllerBase {
  constructor(
    protected readonly service: HealthAndOtherCharacteristicsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HealthAndOtherCharacteristics })
  @nestAccessControl.UseRoles({
    resource: "HealthAndOtherCharacteristics",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createHealthAndOtherCharacteristics(
    @common.Body() data: HealthAndOtherCharacteristicsCreateInput
  ): Promise<HealthAndOtherCharacteristics> {
    return await this.service.createHealthAndOtherCharacteristics({
      data: data,
      select: {
        accessToHealthcare: true,
        chronicDiseases: true,
        createdAt: true,
        disabilityStatus: true,
        healthInsuranceStatus: true,
        id: true,
        primaryHealthProvider: true,
        updatedAt: true,
        vaccinationStatus: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [HealthAndOtherCharacteristics] })
  @ApiNestedQuery(HealthAndOtherCharacteristicsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "HealthAndOtherCharacteristics",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async healthAndOtherCharacteristicsItems(
    @common.Req() request: Request
  ): Promise<HealthAndOtherCharacteristics[]> {
    const args = plainToClass(
      HealthAndOtherCharacteristicsFindManyArgs,
      request.query
    );
    return this.service.healthAndOtherCharacteristicsItems({
      ...args,
      select: {
        accessToHealthcare: true,
        chronicDiseases: true,
        createdAt: true,
        disabilityStatus: true,
        healthInsuranceStatus: true,
        id: true,
        primaryHealthProvider: true,
        updatedAt: true,
        vaccinationStatus: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HealthAndOtherCharacteristics })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HealthAndOtherCharacteristics",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async healthAndOtherCharacteristics(
    @common.Param() params: HealthAndOtherCharacteristicsWhereUniqueInput
  ): Promise<HealthAndOtherCharacteristics | null> {
    const result = await this.service.healthAndOtherCharacteristics({
      where: params,
      select: {
        accessToHealthcare: true,
        chronicDiseases: true,
        createdAt: true,
        disabilityStatus: true,
        healthInsuranceStatus: true,
        id: true,
        primaryHealthProvider: true,
        updatedAt: true,
        vaccinationStatus: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HealthAndOtherCharacteristics })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HealthAndOtherCharacteristics",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateHealthAndOtherCharacteristics(
    @common.Param() params: HealthAndOtherCharacteristicsWhereUniqueInput,
    @common.Body() data: HealthAndOtherCharacteristicsUpdateInput
  ): Promise<HealthAndOtherCharacteristics | null> {
    try {
      return await this.service.updateHealthAndOtherCharacteristics({
        where: params,
        data: data,
        select: {
          accessToHealthcare: true,
          chronicDiseases: true,
          createdAt: true,
          disabilityStatus: true,
          healthInsuranceStatus: true,
          id: true,
          primaryHealthProvider: true,
          updatedAt: true,
          vaccinationStatus: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HealthAndOtherCharacteristics })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HealthAndOtherCharacteristics",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteHealthAndOtherCharacteristics(
    @common.Param() params: HealthAndOtherCharacteristicsWhereUniqueInput
  ): Promise<HealthAndOtherCharacteristics | null> {
    try {
      return await this.service.deleteHealthAndOtherCharacteristics({
        where: params,
        select: {
          accessToHealthcare: true,
          chronicDiseases: true,
          createdAt: true,
          disabilityStatus: true,
          healthInsuranceStatus: true,
          id: true,
          primaryHealthProvider: true,
          updatedAt: true,
          vaccinationStatus: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
