/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { LivestockRaisingService } from "../livestockRaising.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LivestockRaisingCreateInput } from "./LivestockRaisingCreateInput";
import { LivestockRaising } from "./LivestockRaising";
import { LivestockRaisingFindManyArgs } from "./LivestockRaisingFindManyArgs";
import { LivestockRaisingWhereUniqueInput } from "./LivestockRaisingWhereUniqueInput";
import { LivestockRaisingUpdateInput } from "./LivestockRaisingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class LivestockRaisingControllerBase {
  constructor(
    protected readonly service: LivestockRaisingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: LivestockRaising })
  @nestAccessControl.UseRoles({
    resource: "LivestockRaising",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createLivestockRaising(
    @common.Body() data: LivestockRaisingCreateInput
  ): Promise<LivestockRaising> {
    return await this.service.createLivestockRaising({
      data: data,
      select: {
        accessToVeterinaryServices: true,
        annualProduction: true,
        commonDiseases: true,
        createdAt: true,
        feedingPractices: true,
        id: true,
        numberOfAnimals: true,
        purposeOfRaising: true,
        typeOfLivestockRaised: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [LivestockRaising] })
  @ApiNestedQuery(LivestockRaisingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "LivestockRaising",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async livestockRaisings(
    @common.Req() request: Request
  ): Promise<LivestockRaising[]> {
    const args = plainToClass(LivestockRaisingFindManyArgs, request.query);
    return this.service.livestockRaisings({
      ...args,
      select: {
        accessToVeterinaryServices: true,
        annualProduction: true,
        commonDiseases: true,
        createdAt: true,
        feedingPractices: true,
        id: true,
        numberOfAnimals: true,
        purposeOfRaising: true,
        typeOfLivestockRaised: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: LivestockRaising })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LivestockRaising",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async livestockRaising(
    @common.Param() params: LivestockRaisingWhereUniqueInput
  ): Promise<LivestockRaising | null> {
    const result = await this.service.livestockRaising({
      where: params,
      select: {
        accessToVeterinaryServices: true,
        annualProduction: true,
        commonDiseases: true,
        createdAt: true,
        feedingPractices: true,
        id: true,
        numberOfAnimals: true,
        purposeOfRaising: true,
        typeOfLivestockRaised: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: LivestockRaising })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LivestockRaising",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateLivestockRaising(
    @common.Param() params: LivestockRaisingWhereUniqueInput,
    @common.Body() data: LivestockRaisingUpdateInput
  ): Promise<LivestockRaising | null> {
    try {
      return await this.service.updateLivestockRaising({
        where: params,
        data: data,
        select: {
          accessToVeterinaryServices: true,
          annualProduction: true,
          commonDiseases: true,
          createdAt: true,
          feedingPractices: true,
          id: true,
          numberOfAnimals: true,
          purposeOfRaising: true,
          typeOfLivestockRaised: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: LivestockRaising })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LivestockRaising",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteLivestockRaising(
    @common.Param() params: LivestockRaisingWhereUniqueInput
  ): Promise<LivestockRaising | null> {
    try {
      return await this.service.deleteLivestockRaising({
        where: params,
        select: {
          accessToVeterinaryServices: true,
          annualProduction: true,
          commonDiseases: true,
          createdAt: true,
          feedingPractices: true,
          id: true,
          numberOfAnimals: true,
          purposeOfRaising: true,
          typeOfLivestockRaised: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
