/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  EducationAndLiteracy as PrismaEducationAndLiteracy,
} from "@prisma/client";

export class EducationAndLiteracyServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.EducationAndLiteracyCountArgs, "select">
  ): Promise<number> {
    return this.prisma.educationAndLiteracy.count(args);
  }

  async educationAndLiteracies(
    args: Prisma.EducationAndLiteracyFindManyArgs
  ): Promise<PrismaEducationAndLiteracy[]> {
    return this.prisma.educationAndLiteracy.findMany(args);
  }
  async educationAndLiteracy(
    args: Prisma.EducationAndLiteracyFindUniqueArgs
  ): Promise<PrismaEducationAndLiteracy | null> {
    return this.prisma.educationAndLiteracy.findUnique(args);
  }
  async createEducationAndLiteracy(
    args: Prisma.EducationAndLiteracyCreateArgs
  ): Promise<PrismaEducationAndLiteracy> {
    return this.prisma.educationAndLiteracy.create(args);
  }
  async updateEducationAndLiteracy(
    args: Prisma.EducationAndLiteracyUpdateArgs
  ): Promise<PrismaEducationAndLiteracy> {
    return this.prisma.educationAndLiteracy.update(args);
  }
  async deleteEducationAndLiteracy(
    args: Prisma.EducationAndLiteracyDeleteArgs
  ): Promise<PrismaEducationAndLiteracy> {
    return this.prisma.educationAndLiteracy.delete(args);
  }
}
